package db_pool

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "db_pool.h"
import "C"
import (
	_ "runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.db_pool_module_entry))
}

//export go_async
func go_async(fn *C.zval, args *C.zend_array) unsafe.Pointer {
	return async(fn, args)
}

//export go_await
func go_await(key *C.zend_string) unsafe.Pointer {
	return frankenphp.PHPValue(await(key))
}
