// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#include <php.h>
#include <Zend/zend_API.h>
#include <Zend/zend_hash.h>
#include <Zend/zend_types.h>
#include <stddef.h>

#include "db_pool.h"
#include "db_pool_arginfo.h"
#include "_cgo_export.h"


PHP_MINIT_FUNCTION(db_pool) {
    
    return SUCCESS;
}

zend_module_entry db_pool_module_entry = {STANDARD_MODULE_HEADER,
                                         "db_pool",
                                         ext_functions,             /* Functions */
                                         PHP_MINIT(db_pool),  /* MINIT */
                                         NULL,                      /* MSHUTDOWN */
                                         NULL,                      /* RINIT */
                                         NULL,                      /* RSHUTDOWN */
                                         NULL,                      /* MINFO */
                                         "1.0.0",                   /* Version */
                                         STANDARD_MODULE_PROPERTIES};
PHP_FUNCTION(async)
{
    zval *fn_callback;
    zend_array *args = NULL;
    ZEND_PARSE_PARAMETERS_START(2, 2)
        Z_PARAM_ZVAL(fn_callback)
        Z_PARAM_ARRAY_HT(args)
    ZEND_PARSE_PARAMETERS_END();
    zend_string *result = go_async(fn_callback, args);
    if (result) {
        RETURN_STR(result);
    }

	RETURN_EMPTY_STRING();
}

